version: '3'

services:
   db:
      image: mysql
      environment:
         MYSQL_PASSWORD: password
         MYSQL_DATABASE: appDB
         MYSQL_USER: user
         MYSQL_ROOT_PASSWORD: password
      volumes:
         - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   server:
      build:
         context: ./
         dockerfile: Dockerfile
      ports:
         -  '8080:80'
      volumes:
         -  ./:/var/www/html
      links:
         -  db
volumes:
   db_data: